name: twitch-helpers
org: skyra
install: true
packagePath: packages/twitch-helpers
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
githubRepo: skyra-project/archid-components
