name: '*next*'
package:
  - '@skyra/http-framework'
  # TODO: Fix name when package.json is created
  # - '@skyra/shared-gateway-pieces'
  # TODO: Fix name when package.json is created
  # - '@skyra/shared-http-pieces'
