name: weather-helpers
org: skyra
install: true
packagePath: packages/weather-helpers
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
githubRepo: skyra-project/archid-components
